server:
  port: 9000
  compression:
    enabled: true
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: dcreukdxnpvruj
    password: 9749bf1e2171addb53fd855eea79c9576fb85b88757c61c982b87db043564be4
    url: jdbc:postgresql://dcreukdxnpvruj:9749bf1e2171addb53fd855eea79c9576fb85b88757c61c982b87db043564be4@ec2-35-174-56-18.compute-1.amazonaws.com:5432/drnk9ndp4t7s1
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect